//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Views.Applicant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterApplication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecruitmentSystem.Localization.Views.Applicant.RegisterApplication", typeof(RegisterApplication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddAvailabilityButton {
            get {
                return ResourceManager.GetString("AddAvailabilityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddCompetenceButton {
            get {
                return ResourceManager.GetString("AddCompetenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available From.
        /// </summary>
        public static string AvailableFromLabel {
            get {
                return ResourceManager.GetString("AvailableFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available From.
        /// </summary>
        public static string AvailableFromTable {
            get {
                return ResourceManager.GetString("AvailableFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available To.
        /// </summary>
        public static string AvailableToLabel {
            get {
                return ResourceManager.GetString("AvailableToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available To.
        /// </summary>
        public static string AvailableToTable {
            get {
                return ResourceManager.GetString("AvailableToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Competences.
        /// </summary>
        public static string CompetenceDropdownLabel {
            get {
                return ResourceManager.GetString("CompetenceDropdownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select competence....
        /// </summary>
        public static string CompetencesPlaceholder {
            get {
                return ResourceManager.GetString("CompetencesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competence.
        /// </summary>
        public static string CompetenceTable {
            get {
                return ResourceManager.GetString("CompetenceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date....
        /// </summary>
        public static string DatepickerPlaceholder {
            get {
                return ResourceManager.GetString("DatepickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string RemoveEntry {
            get {
                return ResourceManager.GetString("RemoveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Application.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Experience.
        /// </summary>
        public static string YearsOfExperienceLabel {
            get {
                return ResourceManager.GetString("YearsOfExperienceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Experience.
        /// </summary>
        public static string YearsOfExperienceTable {
            get {
                return ResourceManager.GetString("YearsOfExperienceTable", resourceCulture);
            }
        }
    }
}
